#!/usr/bin/env python
"""
Django's command-line utility for administrative tasks.
This file is generated manually to allow the application to run
inside a Docker container without relying on django-admin to scaffold
the project. It provides the same entry point as the default
manage.py generated by ``django-admin startproject``.
"""
import os
import sys


def main() -> None:
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'myproject.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()